apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: basic-pass-test
spec:
  steps:
    - name: Dummy pass step
      try:
        - script:
            content: |
              echo "Hello, world! This test will pass."



