apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: assert-deployment
spec:
  steps:
    - try:
        - apply:
            file: deployment.yaml
    - try:
        - assert:
            file: assert-deployment.yaml

